env:
  global:
    - CC_TEST_REPORTER_ID=2b53bcb71527c887284dd02fb8181f3260abb7a2f8e7469f4c226a34219fe115

language: python
python: 3.8

before_install:
  # make depends on poetry
  - pip install poetry

install:
  - make install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: 
  - make check
  - make test

after_script:  
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
